apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: High
  imagePullPolicy: Always
  ingress:
    enableOpenShiftSso: true
  overrides:
    components:
      - name: console
        enabled: true

